### ISSUE TITLE
Crash on getaddrinfo fail

### ISSUE THREAD

**Issue by karshan** [karshan/money-scraper#3]
events.js:183                                                                
      throw er; // Unhandled 'error' event                                   
      ^                                                                      

Error: getaddrinfo EAI_AGAIN secure05c.chase.com:443                         
    at Object._errnoException (util.js:1022:11)                              
    at errnoException (dns.js:55:15)                                         
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

**Comment by karshan** [comment]
Possibly fixed by 0d1589a1f548018406f99f3743899ada57ff6e30
